# Generated by Django 5.2.1 on 2025-05-13 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_days', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('CEO', 'CEO')], default='STAFF', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_attendance.department')),
                ('report_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_report_to', to='emp_attendance.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='emp_attendance.employee'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_duration', models.CharField(choices=[('FULL', 'Full Day Leave'), ('AM', 'Morning Leave'), ('PM', 'Afternoon Leave')], default='FULL', max_length=4)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('app_rej_at', models.DateTimeField(blank=True, null=True)),
                ('app_rej_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approved_rejected', to='emp_attendance.employee')),
                ('request_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request_to', to='emp_attendance.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_attendance.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_attendance.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_days', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='emp_attendance.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_attendance.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('FULL_LEAVE', 'Full Day Leave'), ('AM_LEAVE', 'AM Leave'), ('PM_LEAVE', 'PM Leave')], max_length=20)),
                ('log_date', models.DateField()),
                ('clock_in_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_in_logs', to='emp_attendance.clockmethod')),
                ('clock_out_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_out_logs', to='emp_attendance.clockmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_attendance.employee')),
            ],
            options={
                'ordering': ['-log_date'],
                'unique_together': {('user', 'log_date')},
            },
        ),
    ]
