# Generated by Django 5.2.1 on 2025-05-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0003_alter_attendancelog_user_alter_department_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_attendance.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='emp_attendance.employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='emp_attendance.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='app_rej_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approved_rejected', to='emp_attendance.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request_to', to='emp_attendance.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_attendance.employee'),
        ),
    ]
