# Generated by Django 5.2.1 on 2025-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0005_alter_attendancelog_user_alter_department_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
