# Generated by Django 5.2.1 on 2025-05-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0006_alter_employee_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='job_title',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
    ]
