# Generated by Django 5.2.1 on 2025-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0007_rename_job_title_employee_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
