# Generated by Django 5.2.1 on 2025-05-13 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0008_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='clock_in_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_in_logs', to='emp_attendance.clockmethod'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='clock_out_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_out_logs', to='emp_attendance.clockmethod'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
