# Generated by Django 5.2.1 on 2025-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_duration',
            field=models.CharField(choices=[('FULL_LEAVE', 'Full Day Leave'), ('AM_LEAVE', 'Morning Leave'), ('PM_LEAVE', 'Afternoon Leave')], default='FULL_LEAVE', max_length=10),
        ),
    ]
