# Generated by Django 5.2.1 on 2025-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0011_alter_leaverequest_leave_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='STAFF', max_length=10),
        ),
    ]
